version: '3.8'

networks:
  internal:
    name: "internal-communication"
    driver: "bridge"

services:
  authservice:
    container_name: authservice
    build: 
      context: ./AuthService
      dockerfile: Dockerfile
    networks:
      - internal
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
  prometheus:
    build:
      context: ./infra/prometheus
      dockerfile: Dockerfile
    networks:
      - internal
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana #admin:admin
    networks:
      - internal
    ports:
      - 3030:3000
    volumes:
      - "./infra/grafana/docker-data-mount:/var/lib/grafana"
    depends_on:
      - prometheus
  keycloak:
    image: quay.io/keycloak/keycloak
    networks:
      - internal
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_SCHEMA: public
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    depends_on:
      - postgres
  postgres:
    image: postgres:13-alpine
    networks:
      - internal
    ports:
      - 5432:5432
    volumes:
      - "./infra/postgres/docker-data-mount:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
