version: '3.8'

networks:
  internal:
    name: "internal-communication"
    driver: "bridge"

services:
  authservice:
    container_name: authservice
    build: 
      context: ./AuthService
      dockerfile: Dockerfile
    networks:
      - internal
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
  prometheus:
    build:
      context: ./infra/prometheus
      dockerfile: Dockerfile
    networks:
      - internal
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana #admin:admin
    networks:
      - internal
    ports:
      - 3030:3000
    volumes:
      - "./infra/grafana/docker-data-mount:/var/lib/grafana"
